import { auroraRequest, apiPath } from "../../auth/client.js";
import type { Credentials } from "../../auth/credentials.js";

// Documentos gerados pela IA (outbound). Backend: /dashboard/generated-docs.
// `download` devolve bytes binários; `url` devolve uma signed URL.

export const LIST_GENERATED_DOCS_TOOL = {
  name: "list_generated_docs",
  title: "List generated documents",
  description: "Returns documents generated by AIs, with filters and pagination.",
  inputSchema: {
    type: "object" as const,
    properties: {
      aiId: { type: "string" },
      conversationId: { type: "string" },
      userId: { type: "string" },
      format: { type: "string", enum: ["pdf", "docx", "xlsx", "md", "csv"] },
      status: { type: "string", enum: ["temp", "saved"] },
      from: { type: "string", description: "ISO datetime lower bound." },
      to: { type: "string", description: "ISO datetime upper bound." },
      page: { type: "integer", minimum: 1 },
      pageSize: { type: "integer", minimum: 1, maximum: 100 },
    },
    additionalProperties: false,
  },
} as const;

export const GENERATED_DOCS_STATS_TOOL = {
  name: "generated_docs_stats",
  title: "Generated documents stats",
  description: "Returns usage stats for generated documents (optionally for a single AI).",
  inputSchema: {
    type: "object" as const,
    properties: { aiId: { type: "string", description: "Restrict stats to this AI." } },
    additionalProperties: false,
  },
} as const;

export const GET_GENERATED_DOC_TOOL = {
  name: "get_generated_doc",
  title: "Get generated document",
  description: "Returns metadata of a generated document.",
  inputSchema: {
    type: "object" as const,
    properties: { id: { type: "string", description: "The document's ID." } },
    required: ["id"],
    additionalProperties: false,
  },
} as const;

export const GET_GENERATED_DOC_URL_TOOL = {
  name: "get_generated_doc_url",
  title: "Get generated document URL",
  description: "Returns a signed download URL { url, expiresIn } for a generated document.",
  inputSchema: {
    type: "object" as const,
    properties: { id: { type: "string", description: "The document's ID." } },
    required: ["id"],
    additionalProperties: false,
  },
} as const;

export const DOWNLOAD_GENERATED_DOC_TOOL = {
  name: "download_generated_doc",
  title: "Download generated document",
  description:
    "Downloads the document bytes. Returns `{ contentType, base64 }` (file content base64-encoded). " +
    "For a shareable link prefer get_generated_doc_url.",
  inputSchema: {
    type: "object" as const,
    properties: { id: { type: "string", description: "The document's ID." } },
    required: ["id"],
    additionalProperties: false,
  },
} as const;

export const SAVE_GENERATED_DOC_TOOL = {
  name: "save_generated_doc",
  title: "Save generated document",
  description: "Marks a temporary generated document as saved (keeps it past TTL).",
  inputSchema: {
    type: "object" as const,
    properties: { id: { type: "string", description: "The document's ID." } },
    required: ["id"],
    additionalProperties: false,
  },
} as const;

export const DELETE_GENERATED_DOC_TOOL = {
  name: "delete_generated_doc",
  title: "Delete generated document",
  description: "Permanently deletes a generated document.",
  inputSchema: {
    type: "object" as const,
    properties: { id: { type: "string", description: "The document's ID." } },
    required: ["id"],
    additionalProperties: false,
  },
} as const;

function requireId(args: unknown): string {
  const a = (args ?? {}) as Record<string, unknown>;
  if (!a.id || typeof a.id !== "string") throw new Error("Parameter 'id' is required.");
  return a.id;
}

export async function runListGeneratedDocs(creds: Credentials, args: unknown): Promise<unknown> {
  const a = (args ?? {}) as Record<string, unknown>;
  const params = new URLSearchParams();
  for (const k of ["aiId", "conversationId", "userId", "format", "status", "from", "to", "page", "pageSize"]) {
    const v = a[k];
    if (v !== undefined && v !== null && v !== "") params.set(k, String(v));
  }
  const qs = params.toString() ? `?${params.toString()}` : "";
  return auroraRequest(creds, `/dashboard/generated-docs${qs}`);
}

export async function runGeneratedDocsStats(creds: Credentials, args: unknown): Promise<unknown> {
  const a = (args ?? {}) as Record<string, unknown>;
  const qs = a.aiId && typeof a.aiId === "string" ? `?aiId=${encodeURIComponent(a.aiId)}` : "";
  return auroraRequest(creds, `/dashboard/generated-docs/stats${qs}`);
}

export async function runGetGeneratedDoc(creds: Credentials, args: unknown): Promise<unknown> {
  return auroraRequest(creds, apiPath`/dashboard/generated-docs/${requireId(args)}`);
}

export async function runGetGeneratedDocUrl(creds: Credentials, args: unknown): Promise<unknown> {
  return auroraRequest(creds, apiPath`/dashboard/generated-docs/${requireId(args)}/url`);
}

export async function runDownloadGeneratedDoc(creds: Credentials, args: unknown): Promise<unknown> {
  return auroraRequest(creds, apiPath`/dashboard/generated-docs/${requireId(args)}/download`, {
    responseType: "binary",
  });
}

export async function runSaveGeneratedDoc(creds: Credentials, args: unknown): Promise<unknown> {
  return auroraRequest(creds, apiPath`/dashboard/generated-docs/${requireId(args)}/save`, { method: "POST" });
}

export async function runDeleteGeneratedDoc(creds: Credentials, args: unknown): Promise<{ deleted: true }> {
  await auroraRequest(creds, apiPath`/dashboard/generated-docs/${requireId(args)}`, { method: "DELETE" });
  return { deleted: true };
}
